export const ADD_FAVORITE_FILM = 'ADD_FAVORITE_FILM';
export const ADD_FAVORITE_PERSON = 'ADD_FAVORITE_PERSON';
export const REMOVE_FAVORITE_FILM = 'REMOVE_FAVORITE_FILM';
export const REMOVE_FAVORITE_PERSON = 'REMOVE_FAVORITE_PERSON';